---
- hosts: jenkins-slave
  become: true
  tasks:
  - name: update ubuntu repo and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: install java
    apt:
      name: openjdk-11-jre
      state: present

  - name: download maven packages
    get_url:
    #change following url to latest
      url: https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
    #change file destination as per requirement  
      dest: /home/ubuntu/hostfile
      

  - name: extract maven packages
    unarchive:
      src: /home/ubuntu/hostfile/apache-maven-3.9.5-bin.tar.gz
      dest: /home/ubuntu/hostfile
      remote_src: yes
